"""ASCII art: εικονίδια τύπου δωματίου (8x8) και φιγούρα αποίκου (3x6).

Οι χαρακτήρες είναι αυτοί της palette.PEN_CHARS, ώστε να διορθώνονται με το χέρι:
    '.' = pen 2 (δάπεδο θόλου, το αδιαφανές φόντο του εικονιδίου)
    'W' = pen 5   'C' = pen 10  'b' = pen 1   'y' = pen 12  'O' = pen 7
    'R' = pen 8   'G' = pen 9   'S' = pen 14  'r' = pen 13
"""

from palette import CHAR_PENS

ICON_SIZES = {"s": 12, "m": 16, "l": 20}   # πλευρά ανά μέγεθος θόλου

# Η σειρά είναι ίδια με το R_TYPE στο colony_data.asm.
ROOM_ICONS = [
    ("empty", {                  # 0 - κενό
        12: [
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
        ],
        16: [
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
        ],
        20: [
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("control", {                  # 1 - έλεγχος — οθόνη με κεραία
        12: [
            "...W....W...",
            "....W..W....",
            ".....WW.....",
            "WWWWWWWWWWWW",
            "WCCCCCCCCCCW",
            "WCCCCCCCCCCW",
            "WCCCCCCCCCCW",
            "WCCCCCCCCCCW",
            "WWWWWWWWWWWW",
            ".....WW.....",
            "....WWWW....",
            "...WWWWWW...",
        ],
        16: [
            "....W......W....",
            ".....W....W.....",
            "......W..W......",
            ".......WW.......",
            "WWWWWWWWWWWWWWWW",
            "W..............W",
            "W.CCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCC.W",
            "W..............W",
            "WWWWWWWWWWWWWWWW",
            ".......WW.......",
            "......WWWW......",
            ".....WWWWWW.....",
            "................",
        ],
        20: [
            ".....W..........W...",
            "......W........W....",
            ".......W......W.....",
            "........W....W......",
            ".........W..W.......",
            "..........WW........",
            "WWWWWWWWWWWWWWWWWWWW",
            "W..................W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W..................W",
            "WWWWWWWWWWWWWWWWWWWW",
            ".........WW.........",
            "........WWWW........",
            ".......WWWWWW.......",
            "....................",
        ],
    }),
    ("quarters", {                  # 2 - κοιτώνας — κρεβάτι
        12: [
            "............",
            "WWW.........",
            "WWW.........",
            "WWWWWWWWWWWW",
            "WbbbbbbbbbbW",
            "WbbbbbbbbbbW",
            "WbbbbbbbbbbW",
            "WWWWWWWWWWWW",
            "W..........W",
            "W..........W",
            "WW........WW",
            "............",
        ],
        16: [
            "................",
            ".WWWW...........",
            ".WWWW...........",
            ".WWWW...........",
            "WWWWWWWWWWWWWWWW",
            "WbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbW",
            "WWWWWWWWWWWWWWWW",
            "W..............W",
            "W..............W",
            "WW............WW",
            "WW............WW",
            "................",
            "................",
        ],
        20: [
            "....................",
            ".WWWWW..............",
            ".WWWWW..............",
            ".WWWWW..............",
            ".WWWWW..............",
            "WWWWWWWWWWWWWWWWWWWW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WWWWWWWWWWWWWWWWWWWW",
            "W..................W",
            "W..................W",
            "W..................W",
            "WW................WW",
            "WW................WW",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("canteen", {                  # 3 - καντίνα — μπολ με ατμό
        12: [
            "...O...O....",
            "..O...O.....",
            "...O...O....",
            "............",
            "yyyyyyyyyyyy",
            ".yyyyyyyyyy.",
            "..yyyyyyyy..",
            "...yyyyyy...",
            "....yyyy....",
            "............",
            "............",
            "............",
        ],
        16: [
            "....O.....O.....",
            "...O.....O......",
            "....O.....O.....",
            "...O.....O......",
            "................",
            "yyyyyyyyyyyyyyyy",
            "yyyyyyyyyyyyyyyy",
            ".yyyyyyyyyyyyyy.",
            "..yyyyyyyyyyyy..",
            "...yyyyyyyyyy...",
            "....yyyyyyyy....",
            ".....yyyyyy.....",
            "......yyyy......",
            "................",
            "................",
            "................",
        ],
        20: [
            ".....O.......O......",
            "....O.......O.......",
            ".....O.......O......",
            "....O.......O.......",
            ".....O.......O......",
            "....................",
            "yyyyyyyyyyyyyyyyyyyy",
            "yyyyyyyyyyyyyyyyyyyy",
            ".yyyyyyyyyyyyyyyyyy.",
            "..yyyyyyyyyyyyyyyy..",
            "...yyyyyyyyyyyyyy...",
            "....yyyyyyyyyyyy....",
            ".....yyyyyyyyyy.....",
            "......yyyyyyyy......",
            ".......yyyyyy.......",
            "........yyyy........",
            "....................",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("oxygen", {                  # 4 - οξυγόνο — φούσκες
        12: [
            "..cccc......",
            ".cWWWWc.....",
            ".cWWWWc..cc.",
            ".cWWWWc.cWWc",
            "..cccc..cWWc",
            ".........cc.",
            "....cc......",
            "...cWWc.....",
            "...cWWc.....",
            "....cc......",
            "............",
            "............",
        ],
        16: [
            "..cccccc........",
            ".cWWWWWWc.......",
            "cWWWWWWWWc......",
            "cWWWWWWWWc...cc.",
            "cWWWWWWWWc..cWWc",
            ".cWWWWWWc...cWWc",
            "..cccccc.....cc.",
            "................",
            ".....cccc.......",
            "....cWWWWc......",
            "....cWWWWc......",
            ".....cccc.......",
            "................",
            "................",
            "................",
            "................",
        ],
        20: [
            "....cccccc..........",
            "..ccWWWWWWcc........",
            ".cWWWWWWWWWWc.......",
            ".cWWWWWWWWWWc.......",
            ".cWWWWWWWWWWc.......",
            "..ccWWWWWWcc...cccc.",
            "....cccccc....cWWWWc",
            "..............cWWWWc",
            "...............cccc.",
            "....................",
            "......cccccc........",
            ".....cWWWWWWc.......",
            ".....cWWWWWWc.......",
            ".....cWWWWWWc.......",
            "......cccccc........",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("greenhouse", {                  # 5 - θερμοκήπιο — φυτό σε γλάστρα
        12: [
            "....GGGG....",
            "..GGGGGGGG..",
            ".GGGGGGGGGG.",
            ".GGGGGGGGGG.",
            "..GGGGGGGG..",
            "....GGGG....",
            ".....SS.....",
            ".....SS.....",
            "..SSSSSSSS..",
            "..SSSSSSSS..",
            "...SSSSSS...",
            "............",
        ],
        16: [
            ".....GGGGGG.....",
            "...GGGGGGGGGG...",
            "..GGGGGGGGGGGG..",
            ".GGGGGGGGGGGGGG.",
            ".GGGGGGGGGGGGGG.",
            "..GGGGGGGGGGGG..",
            "...GGGGGGGGGG...",
            ".....GGGGGG.....",
            ".......SS.......",
            ".......SS.......",
            ".......SS.......",
            "..SSSSSSSSSSSS..",
            "..SSSSSSSSSSSS..",
            "...SSSSSSSSSS...",
            "....SSSSSSSS....",
            "................",
        ],
        20: [
            ".......GGGGGG.......",
            ".....GGGGGGGGGG.....",
            "...GGGGGGGGGGGGGG...",
            "..GGGGGGGGGGGGGGGG..",
            ".GGGGGGGGGGGGGGGGGG.",
            ".GGGGGGGGGGGGGGGGGG.",
            "..GGGGGGGGGGGGGGGG..",
            "...GGGGGGGGGGGGGG...",
            ".....GGGGGGGGGG.....",
            ".......GGGGGG.......",
            ".........SS.........",
            ".........SS.........",
            ".........SS.........",
            ".........SS.........",
            "...SSSSSSSSSSSSSS...",
            "...SSSSSSSSSSSSSS...",
            "....SSSSSSSSSSSS....",
            ".....SSSSSSSSSS.....",
            "....................",
            "....................",
        ],
    }),
    ("storage", {                  # 6 - αποθήκη — κιβώτιο με τσέρκια
        12: [
            "OOOOOOOOOOOO",
            "OrrrrrrrrrrO",
            "OrrrrrrrrrrO",
            "OOOOOOOOOOOO",
            "OOOOOOOOOOOO",
            "OrrrrrrrrrrO",
            "OrrrrrrrrrrO",
            "OrrrrrrrrrrO",
            "OOOOOOOOOOOO",
            "OOOOOOOOOOOO",
            "OrrrrrrrrrrO",
            "OOOOOOOOOOOO",
        ],
        16: [
            "OOOOOOOOOOOOOOOO",
            "OrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrO",
            "OOOOOOOOOOOOOOOO",
            "OOOOOOOOOOOOOOOO",
            "OrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrO",
            "OOOOOOOOOOOOOOOO",
            "OOOOOOOOOOOOOOOO",
            "OrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrO",
            "OOOOOOOOOOOOOOOO",
        ],
        20: [
            "OOOOOOOOOOOOOOOOOOOO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OOOOOOOOOOOOOOOOOOOO",
            "OOOOOOOOOOOOOOOOOOOO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OOOOOOOOOOOOOOOOOOOO",
            "OOOOOOOOOOOOOOOOOOOO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OrrrrrrrrrrrrrrrrrrO",
            "OOOOOOOOOOOOOOOOOOOO",
        ],
    }),
    ("airlock", {                  # 7 - airlock — πόρτα με ρίγες κινδύνου
        12: [
            "RRRRRRRRRRRR",
            "yRRyyRRyyRRy",
            "RRyyRRyyRRyy",
            "RyyRRyyRRyyR",
            "yyRRyyRRyyRR",
            "yRRyyRRyyRRy",
            "RRyyRRyyRRyy",
            "RyyRRyyRRyyR",
            "yyRRyyRRyyRR",
            "yRRyyRRyyRRy",
            "RRyyRRyyRRyy",
            "RRRRRRRRRRRR",
        ],
        16: [
            "RRRRRRRRRRRRRRRR",
            "yRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyy",
            "RyyRRyyRRyyRRyyR",
            "yyRRyyRRyyRRyyRR",
            "yRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyy",
            "RyyRRyyRRyyRRyyR",
            "yyRRyyRRyyRRyyRR",
            "yRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyy",
            "RyyRRyyRRyyRRyyR",
            "yyRRyyRRyyRRyyRR",
            "yRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyy",
            "RRRRRRRRRRRRRRRR",
        ],
        20: [
            "RRRRRRRRRRRRRRRRRRRR",
            "yRRyyRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyyRRyy",
            "RyyRRyyRRyyRRyyRRyyR",
            "yyRRyyRRyyRRyyRRyyRR",
            "yRRyyRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyyRRyy",
            "RyyRRyyRRyyRRyyRRyyR",
            "yyRRyyRRyyRRyyRRyyRR",
            "yRRyyRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyyRRyy",
            "RyyRRyyRRyyRRyyRRyyR",
            "yyRRyyRRyyRRyyRRyyRR",
            "yRRyyRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyyRRyy",
            "RyyRRyyRRyyRRyyRRyyR",
            "yyRRyyRRyyRRyyRRyyRR",
            "yRRyyRRyyRRyyRRyyRRy",
            "RRyyRRyyRRyyRRyyRRyy",
            "RRRRRRRRRRRRRRRRRRRR",
        ],
    }),
]

# Φιγούρα αποίκου 3x6. Τοπικό λεξικό: 'X' = pen 6, '.' = διαφανές.
COLONIST_W, COLONIST_H = 3, 6
COLONIST = [
    ".X.",
    ".X.",
    "XXX",
    "XXX",
    "X.X",
    "X.X",
]
COLONIST_LEGEND = {"X": 6, ".": None}   # None = μη σχεδιάζεται


def parse_art(lines, w, h, legend=None, what="art"):
    """ASCII art -> πίνακας [h][w] από pens (ή None για «μη σχεδιάζεται»).

    Αποτυγχάνει με σαφές μήνυμα αν οι διαστάσεις ή οι χαρακτήρες δεν ταιριάζουν.
    """
    if len(lines) != h:
        raise ValueError(f"{what}: {len(lines)} γραμμές αντί για {h}")
    out = []
    for i, line in enumerate(lines):
        if len(line) != w:
            raise ValueError(
                f"{what}: γραμμή {i} έχει {len(line)} χαρακτήρες αντί για {w}: {line!r}")
        row = []
        for j, ch in enumerate(line):
            if legend is not None:
                if ch not in legend:
                    raise ValueError(
                        f"{what}: άγνωστος χαρακτήρας {ch!r} στη γραμμή {i}, στήλη {j}")
                row.append(legend[ch])
            else:
                if ch not in CHAR_PENS:
                    raise ValueError(
                        f"{what}: άγνωστος χαρακτήρας {ch!r} στη γραμμή {i}, στήλη {j}")
                row.append(CHAR_PENS[ch])
        out.append(row)
    return out


# --------------------------------------------------------------------------
# Μηχανήματα
# --------------------------------------------------------------------------
# 8x12 pixels (οπτικά 16x12). Αδιαφανή: κάθονται πάνω στο δάπεδο του θόλου,
# οπότε το '.' είναι pen 2 όπως και στα εικονίδια.
#
# Το δεύτερο πεδίο λέει σε ποια μεγέθη θόλου επιτρέπεται το μηχάνημα.

MACHINE_W, MACHINE_H = 12, 22

MACHINES = [
    ("oxygen", "s", [               # ανακυκλωτής οξυγόνου — δεξαμενή και πίνακας
        "..WWWWWWWW..",
        ".W........W.",
        "W..cccccc..W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W..cccccc..W",
        ".W........W.",
        "..WWWWWWWW..",
        "...W,,,,W...",
        "...W,,,,W...",
        "..WWWWWWWW..",
        "..W,CC,CC,W.",
        "..W,CC,CC,W.",
        "..WWWWWWWW..",
        "...WW..WW...",
        "...WW..WW...",
        "............",
    ]),
    ("iron", "sml", [               # iron από ore — καμίνι με καμινάδες και χοάνη
        "..,,....,,..",
        "..,,....,,..",
        "..,,....,,..",
        ",,,,,,,,,,,,",
        ",..........,",
        ",.,,,,,,,,.,",
        ",.,RRRRRR,.,",
        ",.,RrrrrR,.,",
        ",.,RrRRrR,.,",
        ",.,RrRRrR,.,",
        ",.,RrrrrR,.,",
        ",.,RRRRRR,.,",
        ",.,,,,,,,,.,",
        ",..........,",
        ",,,,,,,,,,,,",
        ".,,,,,,,,,,.",
        ".,.,,,,,,.,.",
        ".,.,rrrr,.,.",
        ".,.,rrrr,.,.",
        ".,.,,,,,,.,.",
        ".,,,,,,,,,,.",
        "..,,,,,,,,..",
    ]),
    ("bioplastic", "sml", [         # bioplastic — δεξαμενή ζύμωσης με στήλη
        ".SSSSSSSSSS.",
        ".S........S.",
        ".S.GGGGGG.S.",
        ".S.GGGGGG.S.",
        ".S.GGGGGG.S.",
        ".S.GGGGGG.S.",
        ".S.GGGGGG.S.",
        ".S.GGGGGG.S.",
        ".S.GGGGGG.S.",
        ".S........S.",
        ".SSSSSSSSSS.",
        "..S,,,,,,S..",
        "..S,GGGG,S..",
        "..S,GGGG,S..",
        "..S,,,,,,S..",
        "..SSSSSSSS..",
        "...S,,,,S...",
        "...S,,,,S...",
        "...SSSSSS...",
        "....S..S....",
        "....S..S....",
        "....SSSS....",
    ]),
    ("weapons", "sml", [            # όπλα — στοιβαγμένα βλήματα και πάγκος
        ",,,,,,,,,,,,",
        ",..........,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.RRRRRRR..,",
        ",..........,",
        ",,,,,,,,,,,,",
        ",..........,",
        ",.,,,,,,,,.,",
        ",.,RRRRRR,.,",
        ",.,,,,,,,,.,",
        ",..........,",
        ",,,,,,,,,,,,",
        ".,,,,,,,,,,.",
        ".,........,.",
        ".,,,,,,,,,,.",
        "..,,,,,,,,..",
        "............",
    ]),
    ("processors", "sml", [         # επεξεργαστές — ολοκληρωμένο και δοκιμαστήριο
        "..,.,.,.,...",
        "CCCCCCCCCCCC",
        "C..........C",
        "C.yyyyyyyy.C",
        "C.y......y.C",
        "C.y.yyyy.y.C",
        "C.y.y..y.y.C",
        "C.y.y..y.y.C",
        "C.y.yyyy.y.C",
        "C.y......y.C",
        "C.yyyyyyyy.C",
        "C..........C",
        "CCCCCCCCCCCC",
        "..,.,.,.,...",
        ".,,,,,,,,,,.",
        ".,........,.",
        ".,.CCCCCC.,.",
        ".,.CCCCCC.,.",
        ".,........,.",
        ".,,,,,,,,,,.",
        "..,,,,,,,,..",
        "............",
    ]),
    ("robots", "sml", [             # ρομπότ — κεφάλι, κορμός και πόδια σε γραμμή
        "...WWWWWW...",
        "..W......W..",
        ".W.MM..MM.W.",
        ".W.MM..MM.W.",
        "..W......W..",
        "...WWWWWW...",
        ".....WW.....",
        "..WWWWWWWW..",
        ".W........W.",
        ".W.MMMMMM.W.",
        ".W.M....M.W.",
        ".W.M....M.W.",
        ".W.MMMMMM.W.",
        ".W........W.",
        "..WWWWWWWW..",
        "...W....W...",
        "...W....W...",
        "...W....W...",
        "..WW....WW..",
        ".WWW....WWW.",
        "............",
        "............",
    ]),
    ("food", "sml", [               # φαγητό — καλλιέργεια και δίσκος επεξεργασίας
        ".....GG.....",
        "...GGGGGG...",
        "..GGGGGGGG..",
        ".GGGGGGGGGG.",
        "..GGGGGGGG..",
        "...GGGGGG...",
        ".....SS.....",
        ".....SS.....",
        "...SSSSSS...",
        "..S,,,,,,S..",
        "..S,,,,,,S..",
        "..SSSSSSSS..",
        ".yyyyyyyyyy.",
        ".y........y.",
        ".y.OOOOOO.y.",
        ".y.OOOOOO.y.",
        ".y........y.",
        ".yyyyyyyyyy.",
        "..y,,,,,,y..",
        "..yyyyyyyy..",
        "...y....y...",
        "...y....y...",
    ]),
]
