"""ASCII art: εικονίδια τύπου δωματίου (8x8) και φιγούρα αποίκου (3x6).

Οι χαρακτήρες είναι αυτοί της palette.PEN_CHARS, ώστε να διορθώνονται με το χέρι:
    '.' = pen 2 (δάπεδο θόλου, το αδιαφανές φόντο του εικονιδίου)
    'W' = pen 5   'C' = pen 10  'b' = pen 1   'y' = pen 12  'O' = pen 7
    'R' = pen 8   'G' = pen 9   'S' = pen 14  'r' = pen 13
"""

from palette import CHAR_PENS

ICON_SIZES = {"s": 12, "m": 16, "l": 20}   # πλευρά ανά μέγεθος θόλου

# Οι τύποι δωματίου. Οι 8 πρώτοι ΔΕΝ μετακινούνται — οι δείκτες τους είναι
# ήδη σε χρήση. Οι νέοι μπαίνουν στο τέλος.

# Η σειρά είναι ίδια με το R_TYPE στο colony_data.asm.
ROOM_ICONS = [
    ("empty", {                  # 0 - κενό
        12: [
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
            "............",
        ],
        16: [
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
            "................",
        ],
        20: [
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("control", {                  # 1 - έλεγχος — οθόνη με κεραία
        12: [
            "...W....W...",
            "....W..W....",
            ".....WW.....",
            "WWWWWWWWWWWW",
            "WCCCCCCCCCCW",
            "WCCCCCCCCCCW",
            "WCCCCCCCCCCW",
            "WCCCCCCCCCCW",
            "WWWWWWWWWWWW",
            ".....WW.....",
            "....WWWW....",
            "...WWWWWW...",
        ],
        16: [
            "....W......W....",
            ".....W....W.....",
            "......W..W......",
            ".......WW.......",
            "WWWWWWWWWWWWWWWW",
            "W..............W",
            "W.CCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCC.W",
            "W..............W",
            "WWWWWWWWWWWWWWWW",
            ".......WW.......",
            "......WWWW......",
            ".....WWWWWW.....",
            "................",
        ],
        20: [
            ".....W..........W...",
            "......W........W....",
            ".......W......W.....",
            "........W....W......",
            ".........W..W.......",
            "..........WW........",
            "WWWWWWWWWWWWWWWWWWWW",
            "W..................W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W.CCCCCCCCCCCCCCCC.W",
            "W..................W",
            "WWWWWWWWWWWWWWWWWWWW",
            ".........WW.........",
            "........WWWW........",
            ".......WWWWWW.......",
            "....................",
        ],
    }),
    ("quarters", {                  # 2 - κοιτώνας — κρεβάτι
        12: [
            "............",
            "WWW.........",
            "WWW.........",
            "WWWWWWWWWWWW",
            "WbbbbbbbbbbW",
            "WbbbbbbbbbbW",
            "WbbbbbbbbbbW",
            "WWWWWWWWWWWW",
            "W..........W",
            "W..........W",
            "WW........WW",
            "............",
        ],
        16: [
            "................",
            ".WWWW...........",
            ".WWWW...........",
            ".WWWW...........",
            "WWWWWWWWWWWWWWWW",
            "WbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbW",
            "WWWWWWWWWWWWWWWW",
            "W..............W",
            "W..............W",
            "WW............WW",
            "WW............WW",
            "................",
            "................",
        ],
        20: [
            "....................",
            ".WWWWW..............",
            ".WWWWW..............",
            ".WWWWW..............",
            ".WWWWW..............",
            "WWWWWWWWWWWWWWWWWWWW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WbbbbbbbbbbbbbbbbbbW",
            "WWWWWWWWWWWWWWWWWWWW",
            "W..................W",
            "W..................W",
            "W..................W",
            "WW................WW",
            "WW................WW",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("canteen", {                  # 3 - καντίνα — μπολ με ατμό
        12: [
            "...P...P....",
            "..P...P.....",
            "...P...P....",
            "............",
            "YYYYYYYYYYYY",
            ".YYYYYYYYYY.",
            "..YYYYYYYY..",
            "...YYYYYY...",
            "....YYYY....",
            "............",
            "............",
            "............",
        ],
        16: [
            "....P.....P.....",
            "...P.....P......",
            "....P.....P.....",
            "...P.....P......",
            "................",
            "YYYYYYYYYYYYYYYY",
            "YYYYYYYYYYYYYYYY",
            ".YYYYYYYYYYYYYY.",
            "..YYYYYYYYYYYY..",
            "...YYYYYYYYYY...",
            "....YYYYYYYY....",
            ".....YYYYYY.....",
            "......YYYY......",
            "................",
            "................",
            "................",
        ],
        20: [
            ".....P.......P......",
            "....P.......P.......",
            ".....P.......P......",
            "....P.......P.......",
            ".....P.......P......",
            "....................",
            "YYYYYYYYYYYYYYYYYYYY",
            "YYYYYYYYYYYYYYYYYYYY",
            ".YYYYYYYYYYYYYYYYYY.",
            "..YYYYYYYYYYYYYYYY..",
            "...YYYYYYYYYYYYYY...",
            "....YYYYYYYYYYYY....",
            ".....YYYYYYYYYY.....",
            "......YYYYYYYY......",
            ".......YYYYYY.......",
            "........YYYY........",
            "....................",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("oxygen", {                  # 4 - οξυγόνο — φούσκες
        12: [
            "..cccc......",
            ".cWWWWc.....",
            ".cWWWWc..cc.",
            ".cWWWWc.cWWc",
            "..cccc..cWWc",
            ".........cc.",
            "....cc......",
            "...cWWc.....",
            "...cWWc.....",
            "....cc......",
            "............",
            "............",
        ],
        16: [
            "..cccccc........",
            ".cWWWWWWc.......",
            "cWWWWWWWWc......",
            "cWWWWWWWWc...cc.",
            "cWWWWWWWWc..cWWc",
            ".cWWWWWWc...cWWc",
            "..cccccc.....cc.",
            "................",
            ".....cccc.......",
            "....cWWWWc......",
            "....cWWWWc......",
            ".....cccc.......",
            "................",
            "................",
            "................",
            "................",
        ],
        20: [
            "....cccccc..........",
            "..ccWWWWWWcc........",
            ".cWWWWWWWWWWc.......",
            ".cWWWWWWWWWWc.......",
            ".cWWWWWWWWWWc.......",
            "..ccWWWWWWcc...cccc.",
            "....cccccc....cWWWWc",
            "..............cWWWWc",
            "...............cccc.",
            "....................",
            "......cccccc........",
            ".....cWWWWWWc.......",
            ".....cWWWWWWc.......",
            ".....cWWWWWWc.......",
            "......cccccc........",
            "....................",
            "....................",
            "....................",
            "....................",
            "....................",
        ],
    }),
    ("greenhouse", {                  # 5 - θερμοκήπιο — φυτό σε γλάστρα
        12: [
            "....GGGG....",
            "..GGGGGGGG..",
            ".GGGGGGGGGG.",
            ".GGGGGGGGGG.",
            "..GGGGGGGG..",
            "....GGGG....",
            ".....CC.....",
            ".....CC.....",
            "..CCCCCCCC..",
            "..CCCCCCCC..",
            "...CCCCCC...",
            "............",
        ],
        16: [
            ".....GGGGGG.....",
            "...GGGGGGGGGG...",
            "..GGGGGGGGGGGG..",
            ".GGGGGGGGGGGGGG.",
            ".GGGGGGGGGGGGGG.",
            "..GGGGGGGGGGGG..",
            "...GGGGGGGGGG...",
            ".....GGGGGG.....",
            ".......CC.......",
            ".......CC.......",
            ".......CC.......",
            "..CCCCCCCCCCCC..",
            "..CCCCCCCCCCCC..",
            "...CCCCCCCCCC...",
            "....CCCCCCCC....",
            "................",
        ],
        20: [
            ".......GGGGGG.......",
            ".....GGGGGGGGGG.....",
            "...GGGGGGGGGGGGGG...",
            "..GGGGGGGGGGGGGGGG..",
            ".GGGGGGGGGGGGGGGGGG.",
            ".GGGGGGGGGGGGGGGGGG.",
            "..GGGGGGGGGGGGGGGG..",
            "...GGGGGGGGGGGGGG...",
            ".....GGGGGGGGGG.....",
            ".......GGGGGG.......",
            ".........CC.........",
            ".........CC.........",
            ".........CC.........",
            ".........CC.........",
            "...CCCCCCCCCCCCCC...",
            "...CCCCCCCCCCCCCC...",
            "....CCCCCCCCCCCC....",
            ".....CCCCCCCCCC.....",
            "....................",
            "....................",
        ],
    }),
    ("storage", {                  # 6 - αποθήκη — κιβώτιο με τσέρκια
        12: [
            "PPPPPPPPPPPP",
            "PrrrrrrrrrrP",
            "PrrrrrrrrrrP",
            "PPPPPPPPPPPP",
            "PPPPPPPPPPPP",
            "PrrrrrrrrrrP",
            "PrrrrrrrrrrP",
            "PrrrrrrrrrrP",
            "PPPPPPPPPPPP",
            "PPPPPPPPPPPP",
            "PrrrrrrrrrrP",
            "PPPPPPPPPPPP",
        ],
        16: [
            "PPPPPPPPPPPPPPPP",
            "PrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrP",
            "PPPPPPPPPPPPPPPP",
            "PPPPPPPPPPPPPPPP",
            "PrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrP",
            "PPPPPPPPPPPPPPPP",
            "PPPPPPPPPPPPPPPP",
            "PrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrP",
            "PPPPPPPPPPPPPPPP",
        ],
        20: [
            "PPPPPPPPPPPPPPPPPPPP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PPPPPPPPPPPPPPPPPPPP",
            "PPPPPPPPPPPPPPPPPPPP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PPPPPPPPPPPPPPPPPPPP",
            "PPPPPPPPPPPPPPPPPPPP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PrrrrrrrrrrrrrrrrrrP",
            "PPPPPPPPPPPPPPPPPPPP",
        ],
    }),
    ("airlock", {                  # 7 - airlock — πόρτα με ρίγες κινδύνου
        12: [
            "RRRRRRRRRRRR",
            "YRRYYRRYYRRY",
            "RRYYRRYYRRYY",
            "RYYRRYYRRYYR",
            "YYRRYYRRYYRR",
            "YRRYYRRYYRRY",
            "RRYYRRYYRRYY",
            "RYYRRYYRRYYR",
            "YYRRYYRRYYRR",
            "YRRYYRRYYRRY",
            "RRYYRRYYRRYY",
            "RRRRRRRRRRRR",
        ],
        16: [
            "RRRRRRRRRRRRRRRR",
            "YRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYY",
            "RYYRRYYRRYYRRYYR",
            "YYRRYYRRYYRRYYRR",
            "YRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYY",
            "RYYRRYYRRYYRRYYR",
            "YYRRYYRRYYRRYYRR",
            "YRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYY",
            "RYYRRYYRRYYRRYYR",
            "YYRRYYRRYYRRYYRR",
            "YRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYY",
            "RRRRRRRRRRRRRRRR",
        ],
        20: [
            "RRRRRRRRRRRRRRRRRRRR",
            "YRRYYRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYYRRYY",
            "RYYRRYYRRYYRRYYRRYYR",
            "YYRRYYRRYYRRYYRRYYRR",
            "YRRYYRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYYRRYY",
            "RYYRRYYRRYYRRYYRRYYR",
            "YYRRYYRRYYRRYYRRYYRR",
            "YRRYYRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYYRRYY",
            "RYYRRYYRRYYRRYYRRYYR",
            "YYRRYYRRYYRRYYRRYYRR",
            "YRRYYRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYYRRYY",
            "RYYRRYYRRYYRRYYRRYYR",
            "YYRRYYRRYYRRYYRRYYRR",
            "YRRYYRRYYRRYYRRYYRRY",
            "RRYYRRYYRRYYRRYYRRYY",
            "RRRRRRRRRRRRRRRRRRRR",
        ],
    }),
    ("factory", {                  # 8 - εργοστάσιο — γρανάζι
        12: [
            "...WW..WW...",
            "...WW..WW...",
            ".,,,,,,,,,,.",
            ".,,,,,,,,,,.",
            "W,,,,,,,,,,W",
            "W,,,,,,,,,,W",
            "W,,,,,,,,,,W",
            "W,,,,,,,,,,W",
            ".,,,,,,,,,,.",
            ".,,,,,,,,,,.",
            "...WW..WW...",
            "...WW..WW...",
        ],
        16: [
            "....WW....WW....",
            "....WW....WW....",
            "..,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,..",
            "WW,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,WW",
            "..,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,..",
            "....WW....WW....",
            "....WW....WW....",
        ],
        20: [
            ".....WW......WW.....",
            ".....WW......WW.....",
            ".....WW......WW.....",
            "..,,,,,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,,,,,..",
            "WW,,,,,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,,,,,WW",
            "WW,,,,,,,,,,,,,,,,WW",
            "..,,,,,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,,,,,..",
            "..,,,,,,,,,,,,,,,,..",
            ".....WW......WW.....",
            ".....WW......WW.....",
            ".....WW......WW.....",
        ],
    }),
    ("lab", {                  # 9 - εργαστήριο — φιάλη
        12: [
            "...WWWWWW...",
            "....W..W....",
            "....W..W....",
            "....W..W....",
            "...W....W...",
            "...W.GG.W...",
            "..W.GGGG.W..",
            "..W.GGGG.W..",
            ".W.GGGGGG.W.",
            ".W.GGGGGG.W.",
            "..WWWWWWWW..",
            "............",
        ],
        16: [
            "....WWWWWWWW....",
            "......W..W......",
            "......W..W......",
            "......W..W......",
            ".....W....W.....",
            ".....W....W.....",
            "....W.GGGG.W....",
            "....W.GGGG.W....",
            "...W.GGGGGG.W...",
            "...W.GGGGGG.W...",
            "..W.GGGGGGGG.W..",
            "..W.GGGGGGGG.W..",
            ".W.GGGGGGGGGG.W.",
            ".W.GGGGGGGGGG.W.",
            "..WWWWWWWWWWWW..",
            "................",
        ],
        20: [
            "......WWWWWWWW......",
            "........W..W........",
            "........W..W........",
            "........W..W........",
            ".......W....W.......",
            ".......W....W.......",
            "......W......W......",
            "......W.GGGGG.W.....",
            ".....W.GGGGGGG.W....",
            ".....W.GGGGGGG.W....",
            "....W.GGGGGGGGG.W...",
            "....W.GGGGGGGGG.W...",
            "...W.GGGGGGGGGGG.W..",
            "...W.GGGGGGGGGGG.W..",
            "..W.GGGGGGGGGGGGG.W.",
            "..W.GGGGGGGGGGGGG.W.",
            "..W.GGGGGGGGGGGGG.W.",
            "..WWWWWWWWWWWWWWWW..",
            "....................",
            "....................",
        ],
    }),
    ("medbay", {                  # 10 - ιατρείο — σταυρός
        12: [
            "WWWWWWWWWWWW",
            "W..........W",
            "W...RRRR...W",
            "W...RRRR...W",
            "W.RRRRRRRR.W",
            "W.RRRRRRRR.W",
            "W.RRRRRRRR.W",
            "W.RRRRRRRR.W",
            "W...RRRR...W",
            "W...RRRR...W",
            "W..........W",
            "WWWWWWWWWWWW",
        ],
        16: [
            "WWWWWWWWWWWWWWWW",
            "W..............W",
            "W.....RRRR.....W",
            "W.....RRRR.....W",
            "W.....RRRR.....W",
            "W.RRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRR.W",
            "W.....RRRR.....W",
            "W.....RRRR.....W",
            "W.....RRRR.....W",
            "W..............W",
            "W..............W",
            "WWWWWWWWWWWWWWWW",
        ],
        20: [
            "WWWWWWWWWWWWWWWWWWWW",
            "W..................W",
            "W.......RRRR.......W",
            "W.......RRRR.......W",
            "W.......RRRR.......W",
            "W.......RRRR.......W",
            "W.RRRRRRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRRRRRR.W",
            "W.RRRRRRRRRRRRRRRR.W",
            "W.......RRRR.......W",
            "W.......RRRR.......W",
            "W.......RRRR.......W",
            "W.......RRRR.......W",
            "W..................W",
            "W..................W",
            "W..................W",
            "WWWWWWWWWWWWWWWWWWWW",
        ],
    }),
    ("lounge", {                  # 11 - χώρος ανάπαυσης — πολυθρόνα
        12: [
            "............",
            ".WWWWWWWWWW.",
            ".WPPPPPPPPW.",
            ".WPPPPPPPPW.",
            ".WPPPPPPPPW.",
            ".WWPPPPPPWW.",
            "WWPPPPPPPPWW",
            "WWPPPPPPPPWW",
            "WWWWWWWWWWWW",
            ".W........W.",
            ".W........W.",
            "............",
        ],
        16: [
            "................",
            "..WWWWWWWWWWWW..",
            "..WPPPPPPPPPPW..",
            "..WPPPPPPPPPPW..",
            "..WPPPPPPPPPPW..",
            "..WPPPPPPPPPPW..",
            "..WPPPPPPPPPPW..",
            ".WWPPPPPPPPPPWW.",
            "WWPPPPPPPPPPPPWW",
            "WWPPPPPPPPPPPPWW",
            "WWPPPPPPPPPPPPWW",
            "WWWWWWWWWWWWWWWW",
            "..W..........W..",
            "..W..........W..",
            "..W..........W..",
            "................",
        ],
        20: [
            "....................",
            "...WWWWWWWWWWWWWW...",
            "...WPPPPPPPPPPPPW...",
            "...WPPPPPPPPPPPPW...",
            "...WPPPPPPPPPPPPW...",
            "...WPPPPPPPPPPPPW...",
            "...WPPPPPPPPPPPPW...",
            "...WPPPPPPPPPPPPW...",
            "...WPPPPPPPPPPPPW...",
            "..WWPPPPPPPPPPPPWW..",
            ".WWPPPPPPPPPPPPPPWW.",
            ".WWPPPPPPPPPPPPPPWW.",
            ".WWPPPPPPPPPPPPPPWW.",
            ".WWPPPPPPPPPPPPPPWW.",
            ".WWWWWWWWWWWWWWWWWW.",
            "...W............W...",
            "...W............W...",
            "...W............W...",
            "...W............W...",
            "....................",
        ],
    }),
]

# Φιγούρα αποίκου 3x6. Τοπικό λεξικό: 'X' = pen 6, '.' = διαφανές.
COLONIST_W, COLONIST_H = 3, 6
COLONIST = [
    ".X.",
    ".X.",
    "XXX",
    "XXX",
    "X.X",
    "X.X",
]
COLONIST_LEGEND = {"X": 6, ".": None}   # None = μη σχεδιάζεται

# Ρομπότ: ίδιο μέγεθος με τη φιγούρα του αποίκου, ώστε να μπαίνουν στις ίδιες
# θέσεις διαδρόμου. Σε 6x6 οπτικά pixels το χρώμα ξεχωρίζει πριν το περίγραμμα,
# γι' αυτό κάθε τύπος έχει δικό του pen — και κανένα δεν είναι το κίτρινο των
# αποίκων.
ROBOT_LEGEND = {".": None, "R": 13, "P": 15, "C": 10, "c": 3}

ROBOTS = [
    ("carrier", [                   # μεταφορικό — φαρδύ φορτίο, σκούρο κόκκινο
        "RRR",
        "RRR",
        ".R.",
        "RRR",
        "R.R",
        "R.R",
    ]),
    ("driller", [                   # γεωτρητικό — μυτερό τρυπάνι από κάτω
        ".P.",
        "PPP",
        "PPP",
        "PPP",
        ".P.",
        ".P.",
    ]),
    ("engineer", [                  # τεχνικό — κεραίες στο κεφάλι
        "C.C",
        ".C.",
        "CCC",
        "CCC",
        "C.C",
        "C.C",
    ]),
    ("constructor", [               # δομικό — μπράτσο γερανού προς τα πάνω
        "c..",
        "ccc",
        ".c.",
        "ccc",
        "c.c",
        "c.c",
    ]),
]

# Ειδικότητες αποίκων. Ίδιο μέγεθος με τη βασική φιγούρα· κάθε μία έχει δικό της
# pen, γιατί στα 6x6 οπτικά pixels το χρώμα διαβάζεται πριν το σχήμα. Τα pens 1
# και 3 δεν ανήκουν στα ICON_PENS αλλά η παλέτα τα επιτρέπει ρητά όπου
# διαβάζονται — και τα δύο ξεχωρίζουν πάνω στο γκρι δάπεδο του διαδρόμου.
CREW_LEGEND = {".": None, "G": 9, "r": 8, "b": 1}

CREW = [
    ("biologist", [                 # βιολόγος — δίσκος δείγματος στο στήθος
        ".G.",
        ".G.",
        "GGG",
        "GGG",
        ".G.",
        "G.G",
    ]),
    ("medic", [                     # γιατρός — απλωμένα χέρια = σιλουέτα σταυρού
        ".r.",
        "rrr",
        ".r.",
        "rrr",
        "r.r",
        "r.r",
    ]),
    ("guard", [                     # φρουρός — κράνος, φαρδείς ώμοι
        "bbb",
        ".b.",
        "bbb",
        "bbb",
        ".b.",
        "b.b",
    ]),
]

# Οι παραλλαγές κάθε θέσης διαδρόμου, με τη σειρά που αποθηκεύονται.
# Το "" είναι η κενή θέση — χωρίς φιγούρα.
SLOT_FIGURES = ["", "colonist", "biologist", "medic", "guard",
                "carrier", "driller", "engineer", "constructor"]


def parse_art(lines, w, h, legend=None, what="art"):
    """ASCII art -> πίνακας [h][w] από pens (ή None για «μη σχεδιάζεται»).

    Αποτυγχάνει με σαφές μήνυμα αν οι διαστάσεις ή οι χαρακτήρες δεν ταιριάζουν.
    """
    if len(lines) != h:
        raise ValueError(f"{what}: {len(lines)} γραμμές αντί για {h}")
    out = []
    for i, line in enumerate(lines):
        if len(line) != w:
            raise ValueError(
                f"{what}: γραμμή {i} έχει {len(line)} χαρακτήρες αντί για {w}: {line!r}")
        row = []
        for j, ch in enumerate(line):
            if legend is not None:
                if ch not in legend:
                    raise ValueError(
                        f"{what}: άγνωστος χαρακτήρας {ch!r} στη γραμμή {i}, στήλη {j}")
                row.append(legend[ch])
            else:
                if ch not in CHAR_PENS:
                    raise ValueError(
                        f"{what}: άγνωστος χαρακτήρας {ch!r} στη γραμμή {i}, στήλη {j}")
                row.append(CHAR_PENS[ch])
        out.append(row)
    return out


# --------------------------------------------------------------------------
# Μηχανήματα
# --------------------------------------------------------------------------
# 8x12 pixels (οπτικά 16x12). Αδιαφανή: κάθονται πάνω στο δάπεδο του θόλου,
# οπότε το '.' είναι pen 2 όπως και στα εικονίδια.
#
# Το δεύτερο πεδίο λέει σε ποια μεγέθη θόλου επιτρέπεται το μηχάνημα.

MACHINE_W, MACHINE_H = 12, 22

MACHINES = [
    ("oxygen", "s", [               # ανακυκλωτής οξυγόνου — δεξαμενή και πίνακας
        "..WWWWWWWW..",
        ".W........W.",
        "W..cccccc..W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W.cccccccc.W",
        "W..cccccc..W",
        ".W........W.",
        "..WWWWWWWW..",
        "...W,,,,W...",
        "...W,,,,W...",
        "..WWWWWWWW..",
        "..W,CC,CC,W.",
        "..W,CC,CC,W.",
        "..WWWWWWWW..",
        "...WW..WW...",
        "...WW..WW...",
        "............",
    ]),
    ("iron", "sml", [               # iron από ore — καμίνι με καμινάδες και χοάνη
        "..,,....,,..",
        "..,,....,,..",
        "..,,....,,..",
        ",,,,,,,,,,,,",
        ",..........,",
        ",.,,,,,,,,.,",
        ",.,RRRRRR,.,",
        ",.,RrrrrR,.,",
        ",.,RrRRrR,.,",
        ",.,RrRRrR,.,",
        ",.,RrrrrR,.,",
        ",.,RRRRRR,.,",
        ",.,,,,,,,,.,",
        ",..........,",
        ",,,,,,,,,,,,",
        ".,,,,,,,,,,.",
        ".,.,,,,,,.,.",
        ".,.,rrrr,.,.",
        ".,.,rrrr,.,.",
        ".,.,,,,,,.,.",
        ".,,,,,,,,,,.",
        "..,,,,,,,,..",
    ]),
    ("bioplastic", "sml", [         # bioplastic — δεξαμενή ζύμωσης με στήλη
        ".CCCCCCCCCC.",
        ".C........C.",
        ".C.GGGGGG.C.",
        ".C.GGGGGG.C.",
        ".C.GGGGGG.C.",
        ".C.GGGGGG.C.",
        ".C.GGGGGG.C.",
        ".C.GGGGGG.C.",
        ".C.GGGGGG.C.",
        ".C........C.",
        ".CCCCCCCCCC.",
        "..C,,,,,,C..",
        "..C,GGGG,C..",
        "..C,GGGG,C..",
        "..C,,,,,,C..",
        "..CCCCCCCC..",
        "...C,,,,C...",
        "...C,,,,C...",
        "...CCCCCC...",
        "....C..C....",
        "....C..C....",
        "....CCCC....",
    ]),
    ("weapons", "sml", [            # όπλα — στοιβαγμένα βλήματα και πάγκος
        ",,,,,,,,,,,,",
        ",..........,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.R.R.R.R..,",
        ",.RRRRRRR..,",
        ",..........,",
        ",,,,,,,,,,,,",
        ",..........,",
        ",.,,,,,,,,.,",
        ",.,RRRRRR,.,",
        ",.,,,,,,,,.,",
        ",..........,",
        ",,,,,,,,,,,,",
        ".,,,,,,,,,,.",
        ".,........,.",
        ".,,,,,,,,,,.",
        "..,,,,,,,,..",
        "............",
    ]),
    ("processors", "sml", [         # επεξεργαστές — ολοκληρωμένο και δοκιμαστήριο
        "..,.,.,.,...",
        "CCCCCCCCCCCC",
        "C..........C",
        "C.YYYYYYYY.C",
        "C.Y......Y.C",
        "C.Y.YYYY.Y.C",
        "C.Y.Y..Y.Y.C",
        "C.Y.Y..Y.Y.C",
        "C.Y.YYYY.Y.C",
        "C.Y......Y.C",
        "C.YYYYYYYY.C",
        "C..........C",
        "CCCCCCCCCCCC",
        "..,.,.,.,...",
        ".,,,,,,,,,,.",
        ".,........,.",
        ".,.CCCCCC.,.",
        ".,.CCCCCC.,.",
        ".,........,.",
        ".,,,,,,,,,,.",
        "..,,,,,,,,..",
        "............",
    ]),
    ("robots", "sml", [             # ρομπότ — κεφάλι, κορμός και πόδια σε γραμμή
        "...WWWWWW...",
        "..W......W..",
        ".W.PP..PP.W.",
        ".W.PP..PP.W.",
        "..W......W..",
        "...WWWWWW...",
        ".....WW.....",
        "..WWWWWWWW..",
        ".W........W.",
        ".W.PPPPPP.W.",
        ".W.P....P.W.",
        ".W.P....P.W.",
        ".W.PPPPPP.W.",
        ".W........W.",
        "..WWWWWWWW..",
        "...W....W...",
        "...W....W...",
        "...W....W...",
        "..WW....WW..",
        ".WWW....WWW.",
        "............",
        "............",
    ]),
    ("food", "sml", [               # φαγητό — καλλιέργεια και δίσκος επεξεργασίας
        ".....GG.....",
        "...GGGGGG...",
        "..GGGGGGGG..",
        ".GGGGGGGGGG.",
        "..GGGGGGGG..",
        "...GGGGGG...",
        ".....CC.....",
        ".....CC.....",
        "...CCCCCC...",
        "..C,,,,,,C..",
        "..C,,,,,,C..",
        "..CCCCCCCC..",
        ".YYYYYYYYYY.",
        ".Y........Y.",
        ".Y.PPPPPP.Y.",
        ".Y.PPPPPP.Y.",
        ".Y........Y.",
        ".YYYYYYYYYY.",
        "..Y,,,,,,Y..",
        "..YYYYYYYY..",
        "...Y....Y...",
        "...Y....Y...",
    ]),
    ("spares", "sml", [             # ανταλλακτικά — γρανάζια σε ερμάριο
        ",,,,,,,,,,,,",
        ",..........,",
        ",.WW....WW.,",
        ",WWWW..WWWW,",
        ",WWWW..WWWW,",
        ",.WW....WW.,",
        ",..........,",
        ",.WW....WW.,",
        ",WWWW..WWWW,",
        ",WWWW..WWWW,",
        ",.WW....WW.,",
        ",..........,",
        ",,,,,,,,,,,,",
        ",..........,",
        ",.,,,,,,,,.,",
        ",.,WWWWWW,.,",
        ",.,,,,,,,,.,",
        ",..........,",
        ",,,,,,,,,,,,",
        ".,,,,,,,,,,.",
        ".,........,.",
        ".,,,,,,,,,,.",
    ]),
    ("medical", "sml", [            # πάγκος φαρμάκων — medicinal φυτά -> φάρμακα
        ".WWWWWWWWWW.",
        ".W........W.",
        ".W...RR...W.",
        ".W...RR...W.",
        ".W.RRRRRR.W.",
        ".W.RRRRRR.W.",
        ".W...RR...W.",
        ".W...RR...W.",
        ".W........W.",
        ".WWWWWWWWWW.",
        "..W,,,,,,W..",
        "..W,,,,,,W..",
        "..WWWWWWWW..",
        ".,,,,,,,,,,.",
        ".,........,.",
        ".,.PPPPPP.,.",
        ".,.PPPPPP.,.",
        ".,........,.",
        ".,,,,,,,,,,.",
        "..,,,,,,,,..",
        "............",
        "............",
    ]),
    ("vitromeat", "sml", [          # εκτυπωτής κρέατος — δεξαμενή ιστοκαλλιέργειας
        "..WWWWWWWW..",
        ".W........W.",
        "W..PPPPPP..W",
        "W.PPPPPPPP.W",
        "W.PPPPPPPP.W",
        "W.PPPPPPPP.W",
        "W.PPPPPPPP.W",
        "W.PPPPPPPP.W",
        "W..PPPPPP..W",
        ".W........W.",
        "..WWWWWWWW..",
        "...W,,,,W...",
        "...W,,,,W...",
        "..WWWWWWWW..",
        "..W,PP,PP,W.",
        "..W,PP,PP,W.",
        "..WWWWWWWW..",
        "...WW..WW...",
        "...WW..WW...",
        "............",
        "............",
        "............",
    ]),
    ("beds", "sml", [               # κρεβάτια ιατρείου — δύο κλίνες με σταυρό
        "............",
        ".WWWW..WWWW.",
        ".WccW..WccW.",
        ".WccW..WccW.",
        ".WRRW..WRRW.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".W,,W..W,,W.",
        ".WWWW..WWWW.",
        "............",
        "............",
        "............",
    ]),
    ("medstore", "sml", [           # αποθήκη φαρμάκων — ράφια με φιαλίδια
        "............",
        ".WWWWWWWWWW.",
        ".W,,,,,,,,W.",
        ".WRR.RR.RRW.",
        ".WRR.RR.RRW.",
        ".W,,,,,,,,W.",
        ".WPP.PP.PPW.",
        ".WPP.PP.PPW.",
        ".W,,,,,,,,W.",
        ".WRR.RR.RRW.",
        ".WRR.RR.RRW.",
        ".W,,,,,,,,W.",
        ".WWWWWWWWWW.",
        "............",
        "..WWWWWWWW..",
        "..W,,,,,,W..",
        "..W,RRRR,W..",
        "..W,RRRR,W..",
        "..W,,,,,,W..",
        "..WWWWWWWW..",
        "............",
        "............",
    ]),
]



# --------------------------------------------------------------------------
# Ποιο μηχάνημα μπαίνει σε ποιο δωμάτιο
# --------------------------------------------------------------------------
# Μέχρι τώρα κανένας πίνακας δεν έλεγε πού ανήκει κάθε μηχάνημα — μόνο σε ποια
# ΜΕΓΕΘΗ θόλου χωράει (machine_rules). Η αλυσίδα παραγωγής ακολουθεί το
# Planetbase: ο πάγκος φαρμάκων φτιάχνει φάρμακα από `medicinal` φυτά, ο
# εκτυπωτής κρέατος τυπώνει κρέας, και τα δύο στο εργαστήριο· τα κρεβάτια και
# η αποθήκη φαρμάκων στο ιατρείο.
#
# Ονόματα και όχι δείκτες: αν κάποιο μετονομαστεί, η επαλήθευση 13 σπάει το
# build αντί να δείχνει σιωπηλά σε λάθος μηχάνημα.
# Ένα μηχάνημα ΕΠΙΤΡΕΠΕΤΑΙ να ανήκει σε πάνω από ένα δωμάτιο — το DESIGN §6.8
# το κάνει ήδη με τους επεξεργαστές. Αυτό που απαγορεύεται είναι να μη ανήκει
# πουθενά· το ελέγχει η επαλήθευση 13.
ROOM_MACHINES = {
    "control":  ["processors"],
    "canteen":  ["food"],
    "oxygen":   ["oxygen"],
    "factory":  ["iron", "bioplastic", "weapons", "robots", "spares"],
    "lab":      ["processors", "medical", "vitromeat"],
    "medbay":   ["beds", "medstore"],
    # empty, quarters, greenhouse, storage, airlock, lounge δεν δέχονται
    # μηχανήματα· το θερμοκήπιο γεμίζει με φυτά στις ίδιες υποδοχές.
}

# --------------------------------------------------------------------------
# Φυτά
# --------------------------------------------------------------------------
# Τα είδη του Bio-Dome του Planetbase: 5 αμυλούχα, 5 λαχανικά, φαρμακευτικά
# και δέντρα. Ίδιο μέγεθος με τα μηχανήματα (12x22), ώστε να μπαίνουν στις ίδιες
# υποδοχές: ένας θόλος-θερμοκήπιο γεμίζει τις θέσεις του με παρτέρια.
#
# Κάθε φυτό ορίζει τις 18 γραμμές της φυτείας· οι τελευταίες 4 είναι κοινές
# (το παρτέρι) και προστίθενται αυτόματα από το PLANT_BED.

PLANT_W, PLANT_H = 12, 22
PLANT_TOP_H = 18

PLANT_BED = [                       # κοινό παρτέρι: γκρι τελάρο, σκούρο χώμα
    ",,,,,,,,,,,,",
    ",rrrrrrrrrr,",
    ",rrrrrrrrrr,",
    ",,,,,,,,,,,,",
]

# (όνομα, κατηγορία, 18 γραμμές φυτείας)
PLANTS = [
    ("peas", "starch", [
        "............",
        "....GG......",
        "...GGGG.GG..",
        "..GGGGGGGGG.",
        "..GGYYGGYYG.",
        "..GGGGGGGGG.",
        ".GGGGGGGGGGG",
        ".GGYYGGGYYG.",
        ".GGGGGGGGGGG",
        "..GGGGGGGGG.",
        "..GGYYGGYYG.",
        "..GGGGGGGGG.",
        "...GGGGGGG..",
        "....GGGGG...",
        ".....GGG....",
        ".....CC.....",
        ".....CC.....",
        ".....CC.....",
    ]),
    ("rice", "starch", [
        "............",
        "..Y..Y..Y...",
        "..Y..Y..Y...",
        ".CY.CY.CY.C.",
        ".CY.CY.CY.C.",
        ".CC.CC.CC.CC",
        ".CC.CC.CC.CC",
        "CCC.CC.CC.CC",
        "CCC.CC.CC.CC",
        "CCC.CC.CC.CC",
        "CCC.CC.CC.CC",
        ".CC.CC.CC.CC",
        ".CC.CC.CC.CC",
        ".CC.CC.CC.CC",
        "..C.CC.CC.C.",
        "..C..C..C...",
        "..C..C..C...",
        "............",
    ]),
    ("potatoes", "starch", [
        "............",
        "............",
        "....GG.GG...",
        "..GGGGGGGGG.",
        ".GGGGGGGGGGG",
        ".GGGGGGGGGGG",
        "GGGGGGGGGGGG",
        "GGGGGGGGGGGG",
        ".GGGGGGGGGGG",
        "..GGGGGGGGG.",
        "...GGGGGGG..",
        "....GGGGG...",
        ".....CC.....",
        ".....CC.....",
        "..YY.CC.YY..",
        ".YYYYCCYYYY.",
        ".YYYY..YYYY.",
        "..YY....YY..",
    ]),
    ("wheat", "starch", [
        "............",
        "..P..P..P...",
        ".PPP.PP.PP..",
        ".PPP.PP.PPP.",
        ".PPP.PP.PPP.",
        ".PPP.PP.PPP.",
        "..P..PP..P..",
        "..Y..YY..Y..",
        "..Y..YY..Y..",
        "..Y..YY..Y..",
        ".YY..YY..YY.",
        ".YY..YY..YY.",
        ".YY..YY..YY.",
        ".YY..YY..YY.",
        ".YY..YY..YY.",
        "..Y..YY..Y..",
        "..Y..YY..Y..",
        "............",
    ]),
    ("maize", "starch", [
        "...G....G...",
        "..GG....GG..",
        ".GGG....GGG.",
        ".GGG.YY.GGG.",
        "..GGYPYPGG..",
        "..GGPYPYGG..",
        "...GYPYPG...",
        "...GPYPYG...",
        "...GYPYPG...",
        "..GGPYPYGG..",
        "..GGYPYPGG..",
        ".GGG.YY.GGG.",
        ".GGG.GG.GGG.",
        ".GG..GG..GG.",
        "..G..GG..G..",
        ".....GG.....",
        ".....GG.....",
        ".....GG.....",
    ]),
    ("tomatoes", "veg", [
        "............",
        "....GGGG....",
        "..GGGGGGGG..",
        ".GGGRRGGGGG.",
        ".GGRRRRGGGG.",
        "GGGRRRRGGGGG",
        "GGGGRRGGGGGG",
        "GGGGGGGRRGGG",
        ".GGGGGRRRRG.",
        ".GGGGGRRRRG.",
        ".GGGGGGRRGG.",
        "..GGGGGGGGG.",
        "...GGGGGGG..",
        "....GGGGG...",
        ".....CC.....",
        ".....CC.....",
        ".....CC.....",
        "............",
    ]),
    ("lettuce", "veg", [
        "............",
        "............",
        "...CC..CC...",
        "..CGGCCGGC..",
        ".CGGGGGGGGC.",
        ".CGGGGGGGGC.",
        "CGGGGGGGGGGC",
        "CGGGCGGCGGGC",
        "CGGGGGGGGGGC",
        "CGGGGGGGGGGC",
        ".CGGGGGGGGC.",
        ".CGGGGGGGGC.",
        "..CGGGGGGC..",
        "...CCGGCC...",
        ".....CC.....",
        "............",
        "............",
        "............",
    ]),
    ("onions", "veg", [
        "..C..C..C...",
        "..C..C..C...",
        ".CC.CC.CC...",
        ".CC.CC.CC.C.",
        ".CC.CC.CC.C.",
        "CCC.CC.CC.CC",
        ".CC.CC.CC.CC",
        ".CC.CC.CC.C.",
        "..C..C..C...",
        "............",
        ".YY..YY..YY.",
        "YYYYYYYYYYYY",
        "YYYYYYYYYYYY",
        "YYYYYYYYYYYY",
        "YYYYYYYYYYYY",
        ".YY..YY..YY.",
        "............",
        "............",
    ]),
    ("radishes", "veg", [
        "............",
        "..GG.GG.GG..",
        ".GGGGGGGGGG.",
        ".GGGGGGGGGG.",
        "GGGGGGGGGGGG",
        ".GGGGGGGGGG.",
        "..GGGGGGGG..",
        "...G.GG.G...",
        "............",
        "..RR.RR.RR..",
        ".RRRRRRRRRR.",
        ".RRRRRRRRRR.",
        ".RRRRRRRRRR.",
        "..RR.RR.RR..",
        "..rr.rr.rr..",
        "...r..r..r..",
        "............",
        "............",
    ]),
    ("mushrooms", "veg", [
        "............",
        "............",
        "...PPPP.....",
        "..PPPPPP....",
        ".PPPPPPPP...",
        ".PPPPPPPP.PP",
        "...WWWW..PPP",
        "...WWWW.PPPP",
        "...WWWW.PPPP",
        "...WWWW..WWW",
        ".PPPP....WWW",
        "PPPPPP...WWW",
        "PPPPPPP..WWW",
        ".PPPPPP..WWW",
        "..WWWW......",
        "..WWWW......",
        "..WWWW......",
        "............",
    ]),
    ("medicinal", "medicine", [
        "............",
        ".PP..PP..PP.",
        "PPPPPPPPPPPP",
        "PPPPPPPPPPPP",
        ".PP..PP..PP.",
        "..G..GG..G..",
        "..G..GG..G..",
        "..GGGGGGGG..",
        "..G..GG..G..",
        ".GG..GG..GG.",
        ".GG..GG..GG.",
        ".GGGGGGGGGG.",
        ".GG..GG..GG.",
        "..G..GG..G..",
        "..G..GG..G..",
        "..G..GG..G..",
        ".....GG.....",
        "............",
    ]),
    ("tree", "morale", [
        "....GGGG....",
        "..GGGGGGGG..",
        ".GGGGGGGGGG.",
        "GGGGGGGGGGGG",
        "GGGGGGGGGGGG",
        "GGGGGGGGGGGG",
        ".GGGGGGGGGG.",
        "..GGGGGGGG..",
        "...GGGGGG...",
        "....rrrr....",
        "....rrrr....",
        "....rrrr....",
        "....rrrr....",
        "....rrrr....",
        "....rrrr....",
        "...rrrrrr...",
        "..rrrrrrrr..",
        ".rrrrrrrrrr.",
    ]),
]
